### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by OldManCraft** [TheUnderTaker11/More-Avaritia#1]
Caused by: java.lang.NullPointerException
	at morph.avaritia.recipe.extreme.ExtremeCraftingManager.addRecipe(ExtremeCraftingManager.java:78)
	at com.theundertaker11.moreavaritia.compat.quantumflux.QuantumFluxRecipes.init(QuantumFluxRecipes.java:26)
	at com.theundertaker11.moreavaritia.compat.CompatMain.init(CompatMain.java:70)
	at com.theundertaker11.moreavaritia.MoreAvaritiaMain.init(MoreAvaritiaMain.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by TheUnderTaker11** [comment]
Thanks for the report, fixed and uploading a new version now. Didn't think a null item would cause a crash there, but guess I was wrong. Should be up in about 5 minutes
