### ISSUE TITLE
Crash with Avaritia 1.12.2-3.3.0.28

### ISSUE THREAD

**Issue by nickjackson-ff** [TheUnderTaker11/More-Avaritia#19]
https://hastebin.com/yudahadiko.rb

```net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Avaritia (moreavaritia)
Caused by: java.lang.NoClassDefFoundError: morph/avaritia/recipe/extreme/ExtremeCraftingManager
    at com.theundertaker11.moreavaritia.RecipeUtil.addCatalystInput(RecipeUtil.java:31)
    at com.theundertaker11.moreavaritia.compat.refinedstorage.RefinedStorageRecipes.init(RefinedStorageRecipes.java:36)
    at com.theundertaker11.moreavaritia.compat.CompatMain.init(CompatMain.java:98)
    at com.theundertaker11.moreavaritia.MoreAvaritiaMain.init(MoreAvaritiaMain.java:24)```

**Comment by Shibva** [comment]
https://paste.dimdev.org/gaberopiri.mccrash
heres my issue
i was told that is was being caused by applyed enginistics

**Comment by phantom1151** [comment]
i have the same crash as nick please fix

**Comment by Kronos9247** [comment]
Try to use older verions of avaritia. In 1.12 they changed the locations of all the files

**Comment by zyojv** [comment]
The Avaritia developers remove the ExtremeCraftingManager class file from newer builds of Avaritia. In order to play with More Avaritia you need to downgrade Avaritia to older verions or wait until I finish v2.4

**Comment by nickjackson-ff** [comment]
That is understandable. You should probably note this limitation on the mod page or in the file description on CurseForge. Good luck with the development of v2.4.

Latest compatible version of Avaritia: **1.12.2-3.2.0.25**

EDIT: That was fast
